package by.htp.ts.command;

public enum CommandName {
	AUTHORIZATION, REGISTRATION, LOG_OUT,
	
	RETRIEVE_MEDICAL_HISTORY, ADD_TREATMENT,
	
	GO_TO_CURRENT_PAGE, GO_TO_SIGN_IN_PAGE, GO_TO_MAIN_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_MEDICAL_HISTORY
}
